// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/contract.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AnnouncementType int32

const (
	AnnouncementType_HOUSE_WON          AnnouncementType = 0
	AnnouncementType_HOUSE_LOST         AnnouncementType = 1
	AnnouncementType_HOUSE_DEALING      AnnouncementType = 2
	AnnouncementType_HOUSE_PLAYS        AnnouncementType = 18
	AnnouncementType_HOUSE_BLACKJACK    AnnouncementType = 20
	AnnouncementType_PLAYER_BLACKJACK   AnnouncementType = 19
	AnnouncementType_PLAYER_TURNS_START AnnouncementType = 17
	AnnouncementType_PLAYER_TURN_ENDED  AnnouncementType = 12
)

// Enum value maps for AnnouncementType.
var (
	AnnouncementType_name = map[int32]string{
		0:  "HOUSE_WON",
		1:  "HOUSE_LOST",
		2:  "HOUSE_DEALING",
		18: "HOUSE_PLAYS",
		20: "HOUSE_BLACKJACK",
		19: "PLAYER_BLACKJACK",
		17: "PLAYER_TURNS_START",
		12: "PLAYER_TURN_ENDED",
	}
	AnnouncementType_value = map[string]int32{
		"HOUSE_WON":          0,
		"HOUSE_LOST":         1,
		"HOUSE_DEALING":      2,
		"HOUSE_PLAYS":        18,
		"HOUSE_BLACKJACK":    20,
		"PLAYER_BLACKJACK":   19,
		"PLAYER_TURNS_START": 17,
		"PLAYER_TURN_ENDED":  12,
	}
)

func (x AnnouncementType) Enum() *AnnouncementType {
	p := new(AnnouncementType)
	*p = x
	return p
}

func (x AnnouncementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnouncementType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_contract_proto_enumTypes[0].Descriptor()
}

func (AnnouncementType) Type() protoreflect.EnumType {
	return &file_proto_contract_proto_enumTypes[0]
}

func (x AnnouncementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnouncementType.Descriptor instead.
func (AnnouncementType) EnumDescriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{0}
}

type PlayerJoined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Country  string `protobuf:"bytes,3,opt,name=Country,proto3" json:"Country,omitempty"`
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerJoined) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PlayerJoined) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerJoined) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type PlayerLeft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *PlayerLeft) Reset() {
	*x = PlayerLeft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeft) ProtoMessage() {}

func (x *PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeft.ProtoReflect.Descriptor instead.
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerLeft) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PlayerLeft) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type PlayerBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Amount   int32  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *PlayerBet) Reset() {
	*x = PlayerBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBet) ProtoMessage() {}

func (x *PlayerBet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBet.ProtoReflect.Descriptor instead.
func (*PlayerBet) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerBet) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PlayerBet) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PlayerWon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Amount   int32  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *PlayerWon) Reset() {
	*x = PlayerWon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerWon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerWon) ProtoMessage() {}

func (x *PlayerWon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerWon.ProtoReflect.Descriptor instead.
func (*PlayerWon) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerWon) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PlayerWon) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PlayerLost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Amount   int32  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *PlayerLost) Reset() {
	*x = PlayerLost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLost) ProtoMessage() {}

func (x *PlayerLost) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLost.ProtoReflect.Descriptor instead.
func (*PlayerLost) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerLost) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PlayerLost) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PlayerGot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Card     int32  `protobuf:"varint,2,opt,name=Card,proto3" json:"Card,omitempty"`
}

func (x *PlayerGot) Reset() {
	*x = PlayerGot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerGot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGot) ProtoMessage() {}

func (x *PlayerGot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGot.ProtoReflect.Descriptor instead.
func (*PlayerGot) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerGot) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PlayerGot) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

type Announcement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     AnnouncementType `protobuf:"varint,1,opt,name=Type,proto3,enum=proto.AnnouncementType" json:"Type,omitempty"`
	PlayerID string           `protobuf:"bytes,2,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Message  string           `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Announcement) Reset() {
	*x = Announcement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Announcement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Announcement) ProtoMessage() {}

func (x *Announcement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Announcement.ProtoReflect.Descriptor instead.
func (*Announcement) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{6}
}

func (x *Announcement) GetType() AnnouncementType {
	if x != nil {
		return x.Type
	}
	return AnnouncementType_HOUSE_WON
}

func (x *Announcement) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *Announcement) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HouseGot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32 `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *HouseGot) Reset() {
	*x = HouseGot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseGot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseGot) ProtoMessage() {}

func (x *HouseGot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseGot.ProtoReflect.Descriptor instead.
func (*HouseGot) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{7}
}

func (x *HouseGot) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TimeLeft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PLayerID string `protobuf:"bytes,1,opt,name=PLayerID,proto3" json:"PLayerID,omitempty"`
	Amount   int64  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *TimeLeft) Reset() {
	*x = TimeLeft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeLeft) ProtoMessage() {}

func (x *TimeLeft) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeLeft.ProtoReflect.Descriptor instead.
func (*TimeLeft) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{8}
}

func (x *TimeLeft) GetPLayerID() string {
	if x != nil {
		return x.PLayerID
	}
	return ""
}

func (x *TimeLeft) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

//server broadcast to clients
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*Event_PlayerJoined
	//	*Event_PlayerLeft
	//	*Event_PlayerBet
	//	*Event_PlayerWon
	//	*Event_PlayerLost
	//	*Event_PlayerGot
	//	*Event_HouseGot
	//	*Event_TimeLeft
	//	*Event_Announcement
	Payload isEvent_Payload `protobuf_oneof:"payload"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{9}
}

func (m *Event) GetPayload() isEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Event) GetPlayerJoined() *PlayerJoined {
	if x, ok := x.GetPayload().(*Event_PlayerJoined); ok {
		return x.PlayerJoined
	}
	return nil
}

func (x *Event) GetPlayerLeft() *PlayerLeft {
	if x, ok := x.GetPayload().(*Event_PlayerLeft); ok {
		return x.PlayerLeft
	}
	return nil
}

func (x *Event) GetPlayerBet() *PlayerBet {
	if x, ok := x.GetPayload().(*Event_PlayerBet); ok {
		return x.PlayerBet
	}
	return nil
}

func (x *Event) GetPlayerWon() *PlayerWon {
	if x, ok := x.GetPayload().(*Event_PlayerWon); ok {
		return x.PlayerWon
	}
	return nil
}

func (x *Event) GetPlayerLost() *PlayerLost {
	if x, ok := x.GetPayload().(*Event_PlayerLost); ok {
		return x.PlayerLost
	}
	return nil
}

func (x *Event) GetPlayerGot() *PlayerGot {
	if x, ok := x.GetPayload().(*Event_PlayerGot); ok {
		return x.PlayerGot
	}
	return nil
}

func (x *Event) GetHouseGot() *HouseGot {
	if x, ok := x.GetPayload().(*Event_HouseGot); ok {
		return x.HouseGot
	}
	return nil
}

func (x *Event) GetTimeLeft() *TimeLeft {
	if x, ok := x.GetPayload().(*Event_TimeLeft); ok {
		return x.TimeLeft
	}
	return nil
}

func (x *Event) GetAnnouncement() *Announcement {
	if x, ok := x.GetPayload().(*Event_Announcement); ok {
		return x.Announcement
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,1,opt,name=PlayerJoined,proto3,oneof"`
}

type Event_PlayerLeft struct {
	PlayerLeft *PlayerLeft `protobuf:"bytes,2,opt,name=PlayerLeft,proto3,oneof"`
}

type Event_PlayerBet struct {
	PlayerBet *PlayerBet `protobuf:"bytes,3,opt,name=PlayerBet,proto3,oneof"`
}

type Event_PlayerWon struct {
	PlayerWon *PlayerWon `protobuf:"bytes,4,opt,name=PlayerWon,proto3,oneof"`
}

type Event_PlayerLost struct {
	PlayerLost *PlayerLost `protobuf:"bytes,5,opt,name=PlayerLost,proto3,oneof"`
}

type Event_PlayerGot struct {
	PlayerGot *PlayerGot `protobuf:"bytes,6,opt,name=PlayerGot,proto3,oneof"`
}

type Event_HouseGot struct {
	HouseGot *HouseGot `protobuf:"bytes,7,opt,name=HouseGot,proto3,oneof"`
}

type Event_TimeLeft struct {
	TimeLeft *TimeLeft `protobuf:"bytes,8,opt,name=TimeLeft,proto3,oneof"`
}

type Event_Announcement struct {
	Announcement *Announcement `protobuf:"bytes,9,opt,name=Announcement,proto3,oneof"`
}

func (*Event_PlayerJoined) isEvent_Payload() {}

func (*Event_PlayerLeft) isEvent_Payload() {}

func (*Event_PlayerBet) isEvent_Payload() {}

func (*Event_PlayerWon) isEvent_Payload() {}

func (*Event_PlayerLost) isEvent_Payload() {}

func (*Event_PlayerGot) isEvent_Payload() {}

func (*Event_HouseGot) isEvent_Payload() {}

func (*Event_TimeLeft) isEvent_Payload() {}

func (*Event_Announcement) isEvent_Payload() {}

type JoinGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	RoomID   string `protobuf:"bytes,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
}

func (x *JoinGame) Reset() {
	*x = JoinGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGame) ProtoMessage() {}

func (x *JoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGame.ProtoReflect.Descriptor instead.
func (*JoinGame) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{10}
}

func (x *JoinGame) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *JoinGame) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type LeaveGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
}

func (x *LeaveGame) Reset() {
	*x = LeaveGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGame) ProtoMessage() {}

func (x *LeaveGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGame.ProtoReflect.Descriptor instead.
func (*LeaveGame) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveGame) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

type Hit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
}

func (x *Hit) Reset() {
	*x = Hit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hit) ProtoMessage() {}

func (x *Hit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hit.ProtoReflect.Descriptor instead.
func (*Hit) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{12}
}

func (x *Hit) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

type Bet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Amount   int32  `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (x *Bet) Reset() {
	*x = Bet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bet) ProtoMessage() {}

func (x *Bet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bet.ProtoReflect.Descriptor instead.
func (*Bet) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{13}
}

func (x *Bet) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *Bet) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Stay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
}

func (x *Stay) Reset() {
	*x = Stay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stay) ProtoMessage() {}

func (x *Stay) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stay.ProtoReflect.Descriptor instead.
func (*Stay) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{14}
}

func (x *Stay) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

//client actions
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*Action_JoinGame
	//	*Action_LeaveGame
	//	*Action_Hit
	//	*Action_Bet
	//	*Action_Stay
	Payload isAction_Payload `protobuf_oneof:"payload"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_contract_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contract_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_contract_proto_rawDescGZIP(), []int{15}
}

func (m *Action) GetPayload() isAction_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Action) GetJoinGame() *JoinGame {
	if x, ok := x.GetPayload().(*Action_JoinGame); ok {
		return x.JoinGame
	}
	return nil
}

func (x *Action) GetLeaveGame() *LeaveGame {
	if x, ok := x.GetPayload().(*Action_LeaveGame); ok {
		return x.LeaveGame
	}
	return nil
}

func (x *Action) GetHit() *Hit {
	if x, ok := x.GetPayload().(*Action_Hit); ok {
		return x.Hit
	}
	return nil
}

func (x *Action) GetBet() *Bet {
	if x, ok := x.GetPayload().(*Action_Bet); ok {
		return x.Bet
	}
	return nil
}

func (x *Action) GetStay() *Stay {
	if x, ok := x.GetPayload().(*Action_Stay); ok {
		return x.Stay
	}
	return nil
}

type isAction_Payload interface {
	isAction_Payload()
}

type Action_JoinGame struct {
	JoinGame *JoinGame `protobuf:"bytes,1,opt,name=JoinGame,proto3,oneof"`
}

type Action_LeaveGame struct {
	LeaveGame *LeaveGame `protobuf:"bytes,2,opt,name=LeaveGame,proto3,oneof"`
}

type Action_Hit struct {
	Hit *Hit `protobuf:"bytes,3,opt,name=Hit,proto3,oneof"`
}

type Action_Bet struct {
	Bet *Bet `protobuf:"bytes,4,opt,name=Bet,proto3,oneof"`
}

type Action_Stay struct {
	Stay *Stay `protobuf:"bytes,5,opt,name=Stay,proto3,oneof"`
}

func (*Action_JoinGame) isAction_Payload() {}

func (*Action_LeaveGame) isAction_Payload() {}

func (*Action_Hit) isAction_Payload() {}

func (*Action_Bet) isAction_Payload() {}

func (*Action_Stay) isAction_Payload() {}

var File_proto_contract_proto protoreflect.FileDescriptor

var file_proto_contract_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a,
	0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22,
	0x44, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42,
	0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x57, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4c, 0x6f, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x09, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x47, 0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x43, 0x61, 0x72, 0x64, 0x22, 0x71, 0x0a, 0x0c, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6e, 0x6e,
	0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a, 0x08, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x47, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3e, 0x0a,
	0x08, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x4c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x4c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xe6, 0x03,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e,
	0x65, 0x64, 0x12, 0x33, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x42, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x48, 0x00, 0x52, 0x09,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x57, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x57, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x57, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x0a, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x6f, 0x73, 0x74,
	0x12, 0x30, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x6f, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x47, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47,
	0x6f, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x6f, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x47, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x08, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x47, 0x6f,
	0x74, 0x12, 0x2d, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x4c, 0x65, 0x66, 0x74, 0x48, 0x00, 0x52, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x65, 0x66, 0x74,
	0x12, 0x39, 0x0a, 0x0c, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3e, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x09, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x22,
	0x21, 0x0a, 0x03, 0x48, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x44, 0x22, 0x39, 0x0a, 0x03, 0x42, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x22, 0x0a,
	0x04, 0x53, 0x74, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x22, 0xd7, 0x01, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x08,
	0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x48,
	0x00, 0x52, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x48, 0x00, 0x52, 0x09, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x03, 0x48, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x48, 0x69, 0x74, 0x48, 0x00, 0x52, 0x03, 0x48, 0x69, 0x74, 0x12, 0x1e, 0x0a,
	0x03, 0x42, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x65, 0x74, 0x48, 0x00, 0x52, 0x03, 0x42, 0x65, 0x74, 0x12, 0x21, 0x0a,
	0x04, 0x53, 0x74, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x79, 0x48, 0x00, 0x52, 0x04, 0x53, 0x74, 0x61, 0x79,
	0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0xaf, 0x01, 0x0a, 0x10,
	0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0d, 0x0a, 0x09, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x5f, 0x57, 0x4f, 0x4e, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x5f, 0x4c, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x5f, 0x44, 0x45, 0x41, 0x4c, 0x49, 0x4e, 0x47,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x5f, 0x50, 0x4c, 0x41, 0x59,
	0x53, 0x10, 0x12, 0x12, 0x13, 0x0a, 0x0f, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x5f, 0x42, 0x4c, 0x41,
	0x43, 0x4b, 0x4a, 0x41, 0x43, 0x4b, 0x10, 0x14, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x4c, 0x41, 0x59,
	0x45, 0x52, 0x5f, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x4a, 0x41, 0x43, 0x4b, 0x10, 0x13, 0x12, 0x16,
	0x0a, 0x12, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x54, 0x55, 0x52, 0x4e, 0x53, 0x5f, 0x53,
	0x54, 0x41, 0x52, 0x54, 0x10, 0x11, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x54, 0x55, 0x52, 0x4e, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x0c, 0x32, 0x32, 0x0a,
	0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x28, 0x01, 0x30,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_contract_proto_rawDescOnce sync.Once
	file_proto_contract_proto_rawDescData = file_proto_contract_proto_rawDesc
)

func file_proto_contract_proto_rawDescGZIP() []byte {
	file_proto_contract_proto_rawDescOnce.Do(func() {
		file_proto_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_contract_proto_rawDescData)
	})
	return file_proto_contract_proto_rawDescData
}

var file_proto_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_contract_proto_goTypes = []interface{}{
	(AnnouncementType)(0), // 0: proto.AnnouncementType
	(*PlayerJoined)(nil),  // 1: proto.PlayerJoined
	(*PlayerLeft)(nil),    // 2: proto.PlayerLeft
	(*PlayerBet)(nil),     // 3: proto.PlayerBet
	(*PlayerWon)(nil),     // 4: proto.PlayerWon
	(*PlayerLost)(nil),    // 5: proto.PlayerLost
	(*PlayerGot)(nil),     // 6: proto.PlayerGot
	(*Announcement)(nil),  // 7: proto.Announcement
	(*HouseGot)(nil),      // 8: proto.HouseGot
	(*TimeLeft)(nil),      // 9: proto.TimeLeft
	(*Event)(nil),         // 10: proto.Event
	(*JoinGame)(nil),      // 11: proto.JoinGame
	(*LeaveGame)(nil),     // 12: proto.LeaveGame
	(*Hit)(nil),           // 13: proto.Hit
	(*Bet)(nil),           // 14: proto.Bet
	(*Stay)(nil),          // 15: proto.Stay
	(*Action)(nil),        // 16: proto.Action
}
var file_proto_contract_proto_depIdxs = []int32{
	0,  // 0: proto.Announcement.Type:type_name -> proto.AnnouncementType
	1,  // 1: proto.Event.PlayerJoined:type_name -> proto.PlayerJoined
	2,  // 2: proto.Event.PlayerLeft:type_name -> proto.PlayerLeft
	3,  // 3: proto.Event.PlayerBet:type_name -> proto.PlayerBet
	4,  // 4: proto.Event.PlayerWon:type_name -> proto.PlayerWon
	5,  // 5: proto.Event.PlayerLost:type_name -> proto.PlayerLost
	6,  // 6: proto.Event.PlayerGot:type_name -> proto.PlayerGot
	8,  // 7: proto.Event.HouseGot:type_name -> proto.HouseGot
	9,  // 8: proto.Event.TimeLeft:type_name -> proto.TimeLeft
	7,  // 9: proto.Event.Announcement:type_name -> proto.Announcement
	11, // 10: proto.Action.JoinGame:type_name -> proto.JoinGame
	12, // 11: proto.Action.LeaveGame:type_name -> proto.LeaveGame
	13, // 12: proto.Action.Hit:type_name -> proto.Hit
	14, // 13: proto.Action.Bet:type_name -> proto.Bet
	15, // 14: proto.Action.Stay:type_name -> proto.Stay
	16, // 15: proto.Game.Connect:input_type -> proto.Action
	10, // 16: proto.Game.Connect:output_type -> proto.Event
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_contract_proto_init() }
func file_proto_contract_proto_init() {
	if File_proto_contract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerJoined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLeft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerWon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerGot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Announcement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseGot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeLeft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_contract_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_contract_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*Event_PlayerJoined)(nil),
		(*Event_PlayerLeft)(nil),
		(*Event_PlayerBet)(nil),
		(*Event_PlayerWon)(nil),
		(*Event_PlayerLost)(nil),
		(*Event_PlayerGot)(nil),
		(*Event_HouseGot)(nil),
		(*Event_TimeLeft)(nil),
		(*Event_Announcement)(nil),
	}
	file_proto_contract_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*Action_JoinGame)(nil),
		(*Action_LeaveGame)(nil),
		(*Action_Hit)(nil),
		(*Action_Bet)(nil),
		(*Action_Stay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_contract_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_contract_proto_goTypes,
		DependencyIndexes: file_proto_contract_proto_depIdxs,
		EnumInfos:         file_proto_contract_proto_enumTypes,
		MessageInfos:      file_proto_contract_proto_msgTypes,
	}.Build()
	File_proto_contract_proto = out.File
	file_proto_contract_proto_rawDesc = nil
	file_proto_contract_proto_goTypes = nil
	file_proto_contract_proto_depIdxs = nil
}
